### ISSUE TITLE
https://tiles.codefor.de/ is down

### ISSUE THREAD

**Issue by grischard** [codeforberlin/tilestache-config#1]
https://tiles.codefor.de/ isn't loading for me right now, and I'm not sure where to report it. It's been broken for the last 5-6 days.

After a minute, I get:

```
504 Gateway Time-out
nginx/1.4.6 (Ubuntu)
```

**Comment by jochenklar** [comment]
Hey, thanks for reporting. It works again. This is probably the right place to report it. I stil have no clue what causes the problems.

**Comment by tordans** [comment]
This is old and solved.
